image: registry-cybermiles.skymizer.com/cybermiles/environment:ci

stages:
  - build
  - test
  - deploy
  - regression

before_script:
  - git submodule update --init --recursive

build:
  stage: build
  cache:
    paths:
      - build
    policy: push
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j8

test:
  stage: test
  cache:
    paths:
      - build
    policy: pull
  script:
    - ./build/test/soltest -- --no-smt --no-ipc --testpath ./test

deploy:
  stage: deploy
  cache:
    paths:
      - build
    policy: pull
  script:
    - rm -rf lityc
    - cp build/lityc/lityc .
  artifacts:
    paths:
      - lityc
    expire_in: 1 month

regression:
  stage: regression
  script:
    - curl -s -X POST -F "token=$REGRESSION_TRIGGER_TOKEN" -F ref=master https://git-cybermiles.skymizer.com/api/v4/projects/14/trigger/pipeline | jq .
