image: registry-cybermiles.skymizer.com/cybermiles/environment:ci

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - rttest
  - deploy
  - regression

build:
  stage: build
  cache:
    paths:
      - build
    policy: push
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j8

test:
  stage: test
  cache:
    paths:
      - build
    policy: pull
  variables:
    TERM: "linux"
  script:
    - ./build/test/soltest -- --testpath ./test --no-ipc
    - ./test/cmdlineTests.sh

runtime-test:
  stage: rttest
  cache:
    paths:
      - build
    policy: pull
  variables:
    TERM: "linux"
  before_script:
    - curl -sL -o ./aleth --header "Private-Token:"$PRIVATE_TOKEN "https://git-cybermiles.skymizer.com/cybermiles/cpp-ethereum/-/jobs/artifacts/lity/raw/aleth?job=build"
    - chmod +x ./aleth
    - ./aleth --test -d /tmp/rttest >/tmp/rttest.log 2>&1 &
    - while [ ! -S /tmp/rttest/geth.ipc ] ; do sleep 1; done && sleep 2
  script:
    - ./build/test/rttest -- --testpath ./test --ipcpath /tmp/rttest/geth.ipc --show-messages
  after_script:
    - cat /tmp/rttest.log

deploy:
  stage: deploy
  cache:
    paths:
      - build
    policy: pull
  script:
    - rm -rf lityc
    - cp build/lityc/lityc .
  artifacts:
    paths:
      - lityc
    expire_in: 1 month

regression:
  stage: regression
  only:
    - lity
  script:
    - curl -s -X POST -F "token=$REGRESSION_TRIGGER_TOKEN" -F ref=master https://git-cybermiles.skymizer.com/api/v4/projects/14/trigger/pipeline | jq .
